-- AlterTable
ALTER TABLE `user` ADD COLUMN `barangay` VARCHAR(191) NULL,
    ADD COLUMN `city` VARCHAR(191) NULL,
    ADD COLUMN `civilStatus` VARCHAR(191) NULL,
    ADD COLUMN `education` LONGTEXT NULL,
    ADD COLUMN `houseNo` VARCHAR(191) NULL,
    ADD COLUMN `province` VARCHAR(191) NULL,
    ADD COLUMN `references` LONGTEXT NULL,
    ADD COLUMN `street` VARCHAR(191) NULL,
    ADD COLUMN `zipCode` VARCHAR(191) NULL;
